# name: Emoji Commit Checker

# on:
#   push:
#     branches:
#       - main # Modify this to the branch you want to trigger the workflow on

# jobs:
#   check-emoji-commit:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Check for Emoji in Commit Messages
#         run: |
#           COMMIT_MESSAGES=$(git log --format=%B ${{ github.event.before }}..${{ github.sha }})
#           if [[ $COMMIT_MESSAGES =~ ":.*:" ]]; then
#             echo "Commit messages with emojis detected."
#             echo "$COMMIT_MESSAGES"
#             exit 1
#           fi
#         continue-on-error: true
# This is a basic workflow to help you get started with Actions

name: moji reaction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
